### ISSUE TITLE
Test Cluster-API 1.2 alpha/beta tag release 

### ISSUE THREAD

**Issue by joekr** [oracle/cluster-api-provider-oci#104]
**What would you like to be added**:
We need to test the new 1.2 tag release (probably cut 2022-06-20) to make sure CAPOCI won't have issues with the next version release.

Migration guide: https://main.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers

**Why is this needed**:
The version 1.2 of Cluster-API will be released in 2 - 3 weeks so we need to test and make sure we won't have any issues with this.

**Comment by joekr** [comment]
New release tag https://github.com/kubernetes-sigs/cluster-api/tree/v1.2.0-beta.0

**Comment by shyamradhakrishnan** [comment]
Fix issue similar to docker machine controller - https://github.com/kubernetes-sigs/cluster-api/pull/6183/files#diff-1b5b1a47f9db3adfc78f69fc90c91837177c904fbaa332277d9cd4d9bac03d10

**Comment by shyamradhakrishnan** [comment]
change in manager similar to https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a691817f0ea6e8e6624e3c748b33d0058c061fd7/config/manager/manager.yaml?rgh-link-date=2022-02-17T20%3A09%3A43Z#L52

**Comment by shyamradhakrishnan** [comment]
Logger changes as described here - https://main.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers

**Comment by shyamradhakrishnan** [comment]
Check for clusterclass pre-defined network topology for subnets and nsg as described here - https://main.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers

**Comment by shyamradhakrishnan** [comment]
Tested  clusterclass pre-defined network topology for subnets and nsg  with CAPI 1.2.0-beta.0 release and is working fine.

**Comment by shyamradhakrishnan** [comment]
Tested PR blocking e2e tests.

**Comment by shyamradhakrishnan** [comment]
https://github.com/oracle/cluster-api-provider-oci/issues/112 is created to update new version of CAPI when it is released
