### ISSUE TITLE
Investigate and report changes required to support OKE

### ISSUE THREAD

**Issue by shyamradhakrishnan** [oracle/cluster-api-provider-oci#110]
**What would you like to be added**:

Investigate and report changes required to support OKE

**Why is this needed**:
To add OKE support which has been requested by customers

**Comment by joekr** [comment]
This is also being discussed in https://github.com/oracle/cluster-api-provider-oci/discussions/101

**Comment by shyamradhakrishnan** [comment]
Duplicate of #101

**Comment by joekr** [comment]
Sorry wasn't pointing out it was a duplicate 😅 
Just pointing out the discussion exists as well. I'll put this issue in that discussion so those folks are able to track this issue as we.

**Comment by shyamradhakrishnan** [comment]
this ticket was done via doc - https://docs.google.com/document/d/10aDgpZk7OLswVV5e0cIK9GXuckEOQfsT1-MkQDk5X_k/edit# and fixed via various PRs
