### ISSUE TITLE
Add a x-ref/link from the externally managed resourced doc to the custom networking doc

### ISSUE THREAD

**Issue by michael-cico** [oracle/cluster-api-provider-oci#121]
**What would you like to be documented**:

There are 2 documents around externally managed resources, one for all-external resources:

https://oracle.github.io/cluster-api-provider-oci/gs/externally-managed-infrastructure.html

and a custom networking one that describes using an externally-managed VCN only:

https://oracle.github.io/cluster-api-provider-oci/networking/custom-networking.html#example-spec-for-externally-managed-vcn-infrastructure

It would be good to have x-refs between these 2, so users can easily find each case from the other doc.

Alternatively, you can consolidate them into one document with sections on each case.

**Why is this needed**:

Just to make it clearer to users how to manage both cases without having to hunt around the docs for them.

**Comment by joekr** [comment]
Change has been deployed to the docs: https://oracle.github.io/cluster-api-provider-oci/gs/externally-managed-cluster-infrastructure.html
