### ISSUE TITLE
Fix curl command to download CSI storage class

### ISSUE THREAD

**Issue by theabmitra** [oracle/cluster-api-provider-oci#124]
**What would you like to be documented**:
The commands to download CSI sample yamls are shared in a manner so that anyone using them can just copy and paste to see how things work. 
```
curl -L "https://github.com/oracle/oci-cloud-controller-manager/releases/download/${CCM_RELEASE_VERSION}/oci-csi-node-rbac.yaml" -o oci-csi-node-rbac.yaml

curl -L "https://github.com/oracle/oci-cloud-controller-manager/releases/download/${CCM_RELEASE_VERSION}/oci-csi-controller-driver.yaml" -o oci-csi-controller-driver.yaml

curl -L h"ttps://github.com/oracle/oci-cloud-controller-manager/releases/download/${CCM_RELEASE_VERSION}/oci-csi-node-driver.yaml" -o
oci-csi-node-driver.yaml

curl -L curl -L https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/container-storage-interface/storage-class.yaml -o storage-class.yaml
```

There is an extra `curl -L`  in the last instruction here  https://oracle.github.io/cluster-api-provider-oci/gs/install-csi.html

**Why is this needed**:

This is needed so anyone can just use the commands as is, without modifying the instructions to get a basic setup working

**Comment by joekr** [comment]
book as been updated 
<img width="888" alt="image" src="https://user-images.githubusercontent.com/132980/185615233-208cdeed-7c5a-496c-8af1-1b2a97c65469.png">
