### ISSUE TITLE
Invalid secret key name specified for CSI integration

### ISSUE THREAD

**Issue by theabmitra** [oracle/cluster-api-provider-oci#125]
**What would you like to be documented**:
- For CSI integration we need to create a secret `oci-volume-provisioner` with either user_auth OR instance_principal. 
- The documentation https://oracle.github.io/cluster-api-provider-oci/gs/install-csi.html for creating this secret is incorrect and will basically fail the CSI driver bringup. 

- Below is the current command to create the secret
`kubectl  create secret generic oci-volume-provisioner -n kube-system  --from-file=cloud-provider.yaml=cloud-provider-example.yaml`

**Why is this needed**:
- The key used in secret creation is invalid. It should be `config.yaml` and NOT `cloud-provider.yaml` that is basically carried over from CCM documentation
- Modified command 
`kubectl  create secret generic oci-volume-provisioner -n kube-system --from-file=config.yaml=cloud-provider-example.yaml`

**Comment by joekr** [comment]
Book has been updated. 
<img width="888" alt="image" src="https://user-images.githubusercontent.com/132980/185615195-a7788e05-945c-4e96-b116-faa1dd2be204.png">
