### ISSUE TITLE
Ensure webhooks are compatible with CAPI 1.2

### ISSUE THREAD

**Issue by randomvariable** [oracle/cluster-api-provider-oci#137]
As per CAPI 1.2, the webhooks need to be changed as per the upgrade guide:
https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html 

> If infrastructure or bootstrap providers have implemented immutability checks in their InfrastructureMachineTemplate or BootstrapConfigTemplate webhooks, it is required to implement the following changes in order to prevent dry-run to return errors. The implementation requires sigs.k8s.io/controller-runtime in version >= v0.12.3.

This might not be relevant yet if we don't have immutability checks though.

**Comment by shyamradhakrishnan** [comment]
CAPOCI do not have the immutability check, we followed steps in the test https://github.com/kubernetes-sigs/cluster-api/pull/7141 and it ran fine. So no action needed on this ticket.
