### ISSUE TITLE
Add docs for OKE support

### ISSUE THREAD

**Issue by shyamradhakrishnan** [oracle/cluster-api-provider-oci#151]
**What would you like to be documented**:
Add docs for OKE support

**Why is this needed**:

**Comment by joekr** [comment]
I want to make sure we capture known default max values in our documentation as well: https://github.com/oracle/cluster-api-provider-oci/pull/163/files#diff-b21d04dbae7eaed309b71e7feb20847ba5b18d5a854aea3164384e5da6d93f41R617
