### ISSUE TITLE
Add cluster-api-provider-oci to list of providers

### ISSUE THREAD

**Issue by hyder** [oracle/cluster-api-provider-oci#20]
**What would you like to be documented**:
Add cluster-api-provider-oci to list of providers: https://cluster-api.sigs.k8s.io/user/quick-start.html

**Why is this needed**:

**Comment by joekr** [comment]
I think we will need to wait until our provider is in the sig repo in order to complete this.

**Comment by joekr** [comment]
CAPOCI is added to the list of providers book via https://github.com/kubernetes-sigs/cluster-api/pull/6288 but not the quick start yet

**Comment by joekr** [comment]
OCI is now in the [quick start](https://cluster-api.sigs.k8s.io/user/quick-start.html) but not yet in the [provider list ](https://cluster-api.sigs.k8s.io/reference/providers.html)

**Comment by joekr** [comment]
We are now in the list. Closing this issue.
