### ISSUE TITLE
Control plane not getting deleted

### ISSUE THREAD

**Issue by santosh0705** [oracle/cluster-api-provider-oci#208]
**What happened**:
The control plane machine not deleted on cluster delete

**What you expected to happen**:
When you delete the cluster it should delete every node in the cluster

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster with one control plane and one worker node. Once the cluster is in working condition deleting `cluster`, `ocicluster`, `kubeadmcontrolplane`, `ocimachinetemplate` and `kubeadmconfigtemplate` resources leaves the control plane in deleting state but it is not getting deleted. However the worker node get deleted.

**Environment:**

- CAPOCI version: 0.6.0
- Cluster-API version (use `clusterctl version`): v1.3.2
- Kubernetes version (use `kubectl version`): v1.26.1
- Docker version (use `docker info`): 20.10.20
- OS (e.g. from `/etc/os-release`): MacOs / Rancher Desktop

**Comment by shyamradhakrishnan** [comment]
@santosh0705 how are you deleting the cluster? the correct way to delete a cluster is "kubectl delete cluster <cluster-name>" please see this https://cluster-api.sigs.k8s.io/user/quick-start.html
```
IMPORTANT: In order to ensure a proper cleanup of your infrastructure you must always delete the cluster object. Deleting the entire cluster template with kubectl delete -f capi-quickstart.yaml might lead to pending resources to be cleaned up manually.
```

**Comment by santosh0705** [comment]
Thanks @shyamradhakrishnan, Didn't check the doc earlier and jumped into the game :p
It worked.

**Comment by joekr** [comment]
@santosh0705 how were you deleting the cluster? This is more for my knowledge. Thanks 😄
