### ISSUE TITLE
Control plane nodes display provisioned despite desired state not met

### ISSUE THREAD

**Issue by hyder** [oracle/cluster-api-provider-oci#21]
**What happened**:
When setting control plane to 3 nodes, even though the desired state (3 provisioned control plane nodes) has not yet been met, the cluster object has already transitioned to provisioned. This may happen when a control plane node takes longer to provision but the cluster is available.

**What you expected to happen**:
The cluster object should only transition to provisioned after the desired state (i.e. 3 control plane nodes are ready) are met.

**How to reproduce it (as minimally and precisely as possible)**:
export CONTROL_PLANE_MACHINE_COUNT=3 

**Anything else we need to know?**:

**Environment:**

- CAPOCI version: v0.1.0
- Cluster-API version (use `clusterctl version`): v1.0
- Kubernetes version (use `kubectl version`): v1.22.5
- Docker version (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by shyamradhakrishnan** [comment]
This is not a bug wrt capoci, https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/cluster/cluster_controller_phases.go#L53 the cluster is transitioned to provisioned as soon as cluster infra is ready which is infra specified in cluster spec. The Infra is set to ready as soon as cluster controller sets the ready status based on its infra https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/cluster/cluster_controller_phases.go#L53 .
