### ISSUE TITLE
ClusterClass Upgrade Node Rollout Count

### ISSUE THREAD

**Issue by ozhankaraman** [oracle/cluster-api-provider-oci#308]
**What happened**:
I am using a simple cluster class to spin up a kubeadm based oci cluster(https://github.com/oracle/cluster-api-provider-oci/blob/main/templates/cluster-template-cluster-class.yaml). It has 1 master and 2 worker nodes. I started upgrade by updating spec.topology.version and related new image id(worker and master nodes are using image id which gots its value from same variable) on same time. I applied new cluster config and then first clusterclass rolled out 1 master and 1 worker nodes on same time as paralel. When master node upgrade finished(worker node upgrade finishes before master finishes), it upgrades worker nodes again and again while they have already upgraded. So it totally rollout node upgrades 1 master and 4 times of worker nodes so for 3 total of node cluster rolling upgrade runs 5 times.

When I split imageId for master and worker nodes by using variables and when I trigger upgrade only for master node by updating spec.topology.version and related only master node image id while remaining worker nodeId as original, this time it upgrades master nodes with new version and then rolling upgrade each worker node. So when master nodes upgrades it triggers worker nodes upgrade even their image id did not changed.

So is this the expected behaviour? I mean for the first scenario 5 times of rollout for 1 master and 2 worker nodes are expected/desired result?

**What you expected to happen**:
I expect that one master and 2 worker upgrades needs to be done by first upgrading master then upgrade the remaining worker nodes, so total rolling upgrade should be 3 times for a 3 node cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- CAPOCI version: v0.9.0
- Cluster-API version (use `clusterctl version`): 1.5.0
- Kubernetes version (use `kubectl version`): 1.24.8 >> 1.25.9(upgrade)
- Docker version (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by shyamradhakrishnan** [comment]
We tried reproducing this with CAPI 1.5.0 and CAPOCI 0.9.0 but unfortunately could not. Just to be on same page, you have mentioned clusterctl version as 1.5.0, the CAPI version in management cluster is also 1.5.0 right? Can you mention how did you update the imageId and topology.version, did you use kubectl edit? Can you please past the capi controller and capoci controller logs?

**Comment by ozhankaraman** [comment]
I am using clusterapi-operator to deploy capi resources and looks like I only updated kubeadm-control-plane-controller to 1.5.0 and other main components stayed on 1.4.4. After upgrading all capi components to v1.5.0, clusterclass upgrade works like a charm with required count of node rollouts. I am closing issue because as you mentioned it was fixed in latest 1.5.0 version.
