### ISSUE TITLE
Crash loop backoff when creating NLB without Subnet ID

### ISSUE THREAD

**Issue by tozastation** [oracle/cluster-api-provider-oci#348]
**What happened**:

I am sharing this because I had an incident with Cluster API OCI where I got Crash Look Backoff and CR became inoperable.

That code is here https://github.com/oracle/cluster-api-provider-oci/blob/main/cloud/scope/network_load_balancer_reconciler.go#L168

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

- OCICluster spec.networkSpec.skipNetworkManagement is set to true
- spec.networkSpec.vcn.subnets[*].id is not filled
- then, apply OCICluster
- In this state, if spec.networkSpec.vcn.subnets[*].id is not included, *string is called and crashes when creating network load balancer.

**Anything else we need to know?**:

**Proposed amendment**

- Add only those that pass the nil check to controlPlaneEndpointSubnets
  - like this https://github.com/oracle/cluster-api-provider-oci/blob/main/cloud/scope/network_load_balancer_reconciler.go#L191

**Environment:**

- CAPOCI version: v0.14.0
- Cluster-API version (use `clusterctl version`): v1.6.1
- Kubernetes version (use `kubectl version`): v1.26.3
- Docker version (use `docker info`): 24.0.7
- OS (e.g. from `/etc/os-release`): Mac OS 14.2.1 (23C71)

**Comment by tozastation** [comment]
@shyamradhakrishnan 
Hi, I'm Ryo.
If the content is ok, I would like to create an issue and PR about this, is it ok to do so?

**Comment by shyamradhakrishnan** [comment]
@tozastation the NLB requires a subnet to be set. The fix if any, has to be that set a proper error message.

**Comment by tozastation** [comment]
@shyamradhakrishnan 
Thank you replying. 
Yes.

In this case, spec.networkSpec.skipNetworkManagement: true, and the subnet parameter is filled in, but the ID is omitted.
The part I want to do the most is to fix the nil pointer and not be able to change the CR.
When the following code is executed, the CR cannot be changed unless the Failure Policy for Validation, Mutating Webhook is set to Ignore.

example:.
1. https://github.com/oracle/cluster-api-provider-oci/blob/main/cloud/scope/machine.go#L735
2. https://github.com/oracle/cluster-api-provider-oci/blob/main/cloud/scope/network_load_balancer_reconciler.go#L168

I think both codes should have a nil check.
As for errors
1 returns an appropriate error on the next conditional branch
2 It looks like you don't need to add the error since it will return an empty array

On top of that, how about adding a requirement to ValidationWebhook when OCICluster spec.networkSpec.skipNetworkManagement

**Comment by shyamradhakrishnan** [comment]
Than sounds good @tozastation

**Comment by tozastation** [comment]
@shyamradhakrishnan 

thank you!
Can I raise a PR for the nil checks on the Machine and Network Load Balancer?
Validation Webhook is a bit of a mess and I'd like to discuss it separately.

**Comment by shyamradhakrishnan** [comment]
Sure, please go ahead.
