### ISSUE TITLE
Support creating VCN with a list of CIDRs

### ISSUE THREAD

**Issue by zihuaweng** [oracle/cluster-api-provider-oci#368]
**What would you like to be added**:
We currently create our workload cluster using the VCN created with two CIDR blocks, one for node subnet and one for pod subnet. We want to configure the VCN with a list of CIDR blocks using CAPOCI.

**Why is this needed**:
Accept a list of CIDR blocks for VCN configuration.

**Comment by joekr** [comment]
I may be wrong it it looks like the spec as well as the vcn reconciler supports cidr blocks
- template: https://github.com/oracle/cluster-api-provider-oci/blob/main/templates/cluster-template.yaml#L16
- vcn reconciler https://github.com/oracle/cluster-api-provider-oci/blob/b53ef08340b0f763ca776f6e828348cfd9e4662e/cloud/scope/vcn_reconciler.go#L133

Is that what you are looking for?

**Comment by zihuaweng** [comment]
I meant the CIDR for creating the VCN: https://github.com/oracle/cluster-api-provider-oci/blob/b53ef08340b0f763ca776f6e828348cfd9e4662e/api/v1beta1/types.go#L900
Currently the input is a string, could it be a list of CIDR blocks?
https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/CreateVcnDetails

**Comment by shyamradhakrishnan** [comment]
We will raise a PR for this shortly and fix in next release
