### ISSUE TITLE
Displaying CRDs with crdtoyaml

### ISSUE THREAD

**Issue by Skarlso** [oracle/cluster-api-provider-oci#376]
Hello!

I have a tool that is hosted on Github pages and is dynamic. Meaning, it doesn't require me to host it. :)

It can render and generate samples for CRDs, or it can be used to generate a static HTML page. ( I'm working on adding custom CSS injection as well. )

For example displaying your CRD: https://crdtoyaml.com/share?url=https://raw.githubusercontent.com/oracle/cluster-api-provider-oci/main/config/crd/bases/infrastructure.cluster.x-k8s.io_ociclusters.yaml

Will show a lot of information including defaults, enums, patterns, etc.

The CLI part can be used to generate so much more, and add CRD YAML unit tests as well. :)

I'm contacting people who used to use doc.crds.dev. I realise it's a plug, but that thing is abandoned, while mine is under active development, and hosted freely. ( requiring me no infrastructure to maintain ).

Here is the repo: https://github.com/Skarlso/crd-to-sample-yaml.

Sorry for the plug, I don't really get anything from it of course, just trying to help out folks and be useful in general.

Cheers!

**Comment by joekr** [comment]
Thanks for sharing.
