### ISSUE TITLE
Add a section on using external infrastructure in CAPOCI

### ISSUE THREAD

**Issue by shyamradhakrishnan** [oracle/cluster-api-provider-oci#49]
**What would you like to be documented**:

CAPOCI supports externally managed infrastructure feature - https://cluster-api.sigs.k8s.io/developer/providers/v1alpha3-to-v1alpha4.html?highlight=external#required-change-to-support-externally-managed-infrastructure

**Why is this needed**:

This will enable customers to cluster infrastructure outside CAPOCI and then let CAPOCI only manage the instances(nodes).

**Comment by joekr** [comment]
Since it will probably be just a bit until this change lands in main I wanted to document what is needed in this issue.

> If the management cluster is running on OCI (like OKE or standalone Kubernetes cluster on OCI), instance principals can be used:
```
export USE_INSTANCE_PRINCIPAL_B64="$(echo -n "true" | base64 | tr -d '\n')"
```
>Following are the policies which needs to be added to the dynamic group in which the management plane compute instances belong to.
```
Allow dynamic-group <dynamic-group-name> to manage instance-family in compartment <compartment-name>
Allow dynamic-group <dynamic-group-name> to manage load-balancers in compartment <compartment-name>
```

**Comment by shyamradhakrishnan** [comment]
The documentation already exists - https://oracle.github.io/cluster-api-provider-oci/gs/externally-managed-infrastructure.html
