### ISSUE TITLE
Improve how a failure domain is selected for a machine

### ISSUE THREAD

**Issue by joekr** [oracle/cluster-api-provider-oci#60]
**What would you like to be added**:
The current way a machine's failure domain (FD) is selected is [randomly from 1 to 3](https://github.com/joekr/cluster-api-provider-oci/blob/76c3728836fcf66b35087cff77ae9fe95959c9cc/cloud/scope/machine.go#L195). This should be changed to be an "even spread" across FDs where possible.

**Why is this needed**:
This will help improve availability and make sure machines don't randomly end up in the same FDs.

**Comment by shyamradhakrishnan** [comment]
We dont do randomly, we use the failrue domains set in the spec - https://github.com/oracle/cluster-api-provider-oci/blob/main/cloud/scope/machine.go#L189 and if that is not set we use. random one. CAPI sets the failure domain for control plane machines by default, and for node machines, the suggested way is to create N machine deployments and set the failure domain in he deployment. We have a template for that - https://github.com/oracle/cluster-api-provider-oci/blob/main/templates/cluster-template-failure-domain-spread.yaml
